# From the NumPy Documentation
https://numpy.org/doc/stable/user/quickstart.html

***

In [8]:
import numpy as np

In [24]:
a = np.arange(15).reshape(3, 5)


In [25]:
x = np.arange(1,10,2)

In [26]:
a.shape

(3, 5)

In [27]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [28]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [29]:
x.dtype #gives type of elements in array


dtype('int32')

In [30]:
y = np.arange(1.5,10.1,0.02)

In [31]:
y.dtype

dtype('float64')

In [32]:
x.shape


(5,)

In [33]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
y.shape

(430,)

In [36]:
y.reshape(-1,1)

array([[ 1.5 ],
       [ 1.52],
       [ 1.54],
       [ 1.56],
       [ 1.58],
       [ 1.6 ],
       [ 1.62],
       [ 1.64],
       [ 1.66],
       [ 1.68],
       [ 1.7 ],
       [ 1.72],
       [ 1.74],
       [ 1.76],
       [ 1.78],
       [ 1.8 ],
       [ 1.82],
       [ 1.84],
       [ 1.86],
       [ 1.88],
       [ 1.9 ],
       [ 1.92],
       [ 1.94],
       [ 1.96],
       [ 1.98],
       [ 2.  ],
       [ 2.02],
       [ 2.04],
       [ 2.06],
       [ 2.08],
       [ 2.1 ],
       [ 2.12],
       [ 2.14],
       [ 2.16],
       [ 2.18],
       [ 2.2 ],
       [ 2.22],
       [ 2.24],
       [ 2.26],
       [ 2.28],
       [ 2.3 ],
       [ 2.32],
       [ 2.34],
       [ 2.36],
       [ 2.38],
       [ 2.4 ],
       [ 2.42],
       [ 2.44],
       [ 2.46],
       [ 2.48],
       [ 2.5 ],
       [ 2.52],
       [ 2.54],
       [ 2.56],
       [ 2.58],
       [ 2.6 ],
       [ 2.62],
       [ 2.64],
       [ 2.66],
       [ 2.68],
       [ 2.7 ],
       [ 2.72],
       [

In [38]:
x= np.arange(0.0,10.0,0.1)
x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [40]:
y = x**2
y

array([0.000e+00, 1.000e-02, 4.000e-02, 9.000e-02, 1.600e-01, 2.500e-01,
       3.600e-01, 4.900e-01, 6.400e-01, 8.100e-01, 1.000e+00, 1.210e+00,
       1.440e+00, 1.690e+00, 1.960e+00, 2.250e+00, 2.560e+00, 2.890e+00,
       3.240e+00, 3.610e+00, 4.000e+00, 4.410e+00, 4.840e+00, 5.290e+00,
       5.760e+00, 6.250e+00, 6.760e+00, 7.290e+00, 7.840e+00, 8.410e+00,
       9.000e+00, 9.610e+00, 1.024e+01, 1.089e+01, 1.156e+01, 1.225e+01,
       1.296e+01, 1.369e+01, 1.444e+01, 1.521e+01, 1.600e+01, 1.681e+01,
       1.764e+01, 1.849e+01, 1.936e+01, 2.025e+01, 2.116e+01, 2.209e+01,
       2.304e+01, 2.401e+01, 2.500e+01, 2.601e+01, 2.704e+01, 2.809e+01,
       2.916e+01, 3.025e+01, 3.136e+01, 3.249e+01, 3.364e+01, 3.481e+01,
       3.600e+01, 3.721e+01, 3.844e+01, 3.969e+01, 4.096e+01, 4.225e+01,
       4.356e+01, 4.489e+01, 4.624e+01, 4.761e+01, 4.900e+01, 5.041e+01,
       5.184e+01, 5.329e+01, 5.476e+01, 5.625e+01, 5.776e+01, 5.929e+01,
       6.084e+01, 6.241e+01, 6.400e+01, 6.561e+01, 

In [41]:
np.linspace(0.0,10.0,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [42]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
i = np.eye(3)

In [46]:
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
y.dtype

dtype('float64')

In [49]:
i.astype('int64') #cast to integer

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)

In [50]:
i[:,2]

array([0., 0., 1.])